name: Deploy Go Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t nhatnvl/cicd-demo .
      - name: Push image to docker hub
        run: docker push nhatnvl/cicd-demo:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull nhatnvl/cicd-demo:latest
      - name: Delete old container
        run: docker rm -f go-app-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name go-app-container nhatnvl/cicd-demo
